backend:
  name: github
  repo: dwsmith1000/peaceability-website
  branch: main
  auth_endpoint: /api/auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "News & Events"
    label_singular: "News Item"
    folder: "content/news"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
